apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-gatekeeper
  namespace: argocd
spec:
  project: default
  source:
    chart: gatekeeper/gatekeeper
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: v3.6.0
    helm:
      releaseName: gatekeeper

  destination:
    server: https://vcluster-2.host-namespace-2.svc:443
    namespace: gatekeeper-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

