apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-service
  namespace: argocd
spec:
  project: default
source:
  repoURL: 'https://github.com/dockersamples/example-voting-app.git'
  path: k8s-specifications
  targetRevision: HEAD

  destination:
    server: https://vcluster-1.host-namespace-1.svc:443
    namespace: vote-service

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3
